name: Sync Conventions

on:
  schedule:
    - cron: '0 9 * * 1' # Mondays, 09:00 UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: bvandrc/bvandrc-conventions/.github/workflows/sync.yml@main
    with:
      files: all.md
